# Generated by Django 4.2.2 on 2023-06-28 01:11

import NewsQebsite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('urlEndpoint', models.CharField(help_text='url our news', max_length=200)),
                ('tittleText', models.CharField(help_text='Text our news', max_length=200)),
                ('title', models.CharField(help_text='Title our news', max_length=200)),
                ('titleImg', models.ImageField(help_text='Title image our news', upload_to=NewsQebsite.models.News.upload_to)),
                ('firstImg', models.ImageField(help_text='Frst image our news', upload_to=NewsQebsite.models.News.upload_to)),
                ('hoverFirst', models.CharField(help_text='h1 first our news', max_length=200)),
                ('firstText', models.TextField(help_text='Text first our news', max_length=5000)),
                ('hoverSecond', models.CharField(help_text='h1 second our news', max_length=200)),
                ('secondText', models.TextField(help_text='Text second our news', max_length=5000)),
                ('secondImg', models.ImageField(help_text='Second image our news', upload_to=NewsQebsite.models.News.upload_to)),
                ('dataNews', models.DateTimeField(help_text='Text second our news')),
                ('rate', models.IntegerField()),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryNews', models.ForeignKey(help_text='Category second our news ', max_length=5000, on_delete=django.db.models.deletion.CASCADE, to='NewsQebsite.category')),
            ],
            options={
                'ordering': ['-dataNews'],
            },
        ),
    ]
