# Generated by Django 4.2.2 on 2023-06-28 22:18

import NewsQebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsQebsite', '0002_alter_news_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='firstImg',
            field=models.ImageField(blank=True, help_text='Frst image our news', upload_to=NewsQebsite.models.News.upload_to),
        ),
        migrations.AlterField(
            model_name='news',
            name='hoverSecond',
            field=models.CharField(blank=True, help_text='h1 second our news', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='secondImg',
            field=models.ImageField(blank=True, help_text='Second image our news', upload_to=NewsQebsite.models.News.upload_to),
        ),
        migrations.AlterField(
            model_name='news',
            name='secondText',
            field=models.TextField(blank=True, help_text='Text second our news', max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='titleImg',
            field=models.ImageField(blank=True, help_text='Title image our news', upload_to=NewsQebsite.models.News.upload_to),
        ),
    ]
