# Generated by Django 4.2 on 2023-12-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsQebsite', '0005_alter_news_tittletext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categoryNews',
            field=models.CharField(max_length=50),
        ),
    ]
